version: "2.4"
services:
  api:
    image: ${API_IMAGE}
    environment:
      - APP_NAME=blog
      - APP_ENV=local
      - APP_KEY=base64:aL6o/U2e1ziUTXsyTkfzNziH9l4crCISoWMwC8LX4B0=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=blog-test
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - QUEUE_CONNECTION=sync
      - MAIL_MAILER=log
    depends_on:
      migrate:
        condition: service_started

  migrate:
    image: ${API_IMAGE}
    environment:
      - APP_ENV=local
      - APP_KEY=base64:aL6o/U2e1ziUTXsyTkfzNziH9l4crCISoWMwC8LX4B0=
      - APP_DEBUG=true
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=blog-test
      - DB_USERNAME=root
      - DB_PASSWORD=root
