version: '3.8'

services:
  web:
    image: johnliutw/web_service:latest
    container_name: web_service
    deploy:
      replicas: 5
    ports:
      - "8080:80"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    networks:
      - webnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  webnet: